### PR TITLE
Adding animation and fixed bugs

### LINKED ISSUE #37: Scroll doesn't work

### LINKED ISSUE #38: The player's card component is constantly being re-rendered because of setTimeout

### PR DESCRIPTION
**Pull request by xmasterpiecex**

### CODE REVIEW

File: src/pages/EnterPage.tsx [hunk 1]
```diff
@@ -82,7 +82,7 @@ export default function EnterPage() {
         sx={{
           display: "flex",
           width: "100%",
-          position: 'fixed',
+          position: 'relative',
```
Comment (xmasterpiecex) [inline src/pages/EnterPage.tsx:85]: Here fixed scroll

File: src/components/gameScene/playerComp/PlayerCard.tsx
Comment (uspiritwolf) [inline src/components/gameScene/playerComp/PlayerCard.tsx:1]: Please revert changes from this file, and make a fix with the correct approach in a new branch

Also, try to have changes for only one atomic feature per pull request.

File: src/components/gameScene/animatedComp/AnimatedScrollForThemes.tsx [hunk 2]
```diff
@@ -0,0 +1,65 @@
...
+      }}
+    >
+      {themes.map((item) => {
+        return (
+          <Typography
+            sx={{
+              position: 'relative',
+              animation: `${breatheAnimation} ${themes.length * 2}s linear both`,
+            }}
+            key={Math.floor(Math.random() * 99999)}
```
Comment (uspiritwolf) [inline src/components/gameScene/animatedComp/AnimatedScrollForThemes.tsx]: Why is randomness necessary here? 

If a unique key is required, then 
- why not use the index from the map function?
- is a bad approach because there is a chance of key collision not 0% with Math.random

File: src/components/gameScene/animatedComp/AnimatedScrollForThemes.tsx [hunk 3]
```diff
@@ -0,0 +1,65 @@
...
+  const themes: string[] = [];
+
+  for (const theme in props.questions) {
+    themes.push(theme)
+  }
+
+  useEffect(() => {
+    const t = setTimeout(() => {
+      props.changeIdx()
+    }, themes.length * 1500)
```
Comment (uspiritwolf) [inline src/components/gameScene/animatedComp/AnimatedScrollForThemes.tsx]: Please avoid magic number

It's better to make code that documents itself, for example:
```
const speed = 100
const heightItem = 150
const durationPerItem = heightItem / speed;
const totalDurationMs = themes.length *  durationPerItem * 1000
```

Comment (uspiritwolf) [reply src/components/gameScene/animatedComp/AnimatedScrollForThemes.tsx]: This allows a better understanding of what the parameters affect, and a better understanding of how to change them in case there are too many or too few themes.

**Review by uspiritwolf — CHANGES_REQUESTED** [review]

File: src/components/gameScene/playerComp/PlayerCard.tsx
Comment (uspiritwolf) [reply src/components/gameScene/playerComp/PlayerCard.tsx:1]: By the correct approach, I mean either modify it to fix the problem with re-rendered, or remove it completely if it is not needed

File: src/components/gameScene/animatedComp/AnimatedScrollForThemes.tsx (hunk 3 above)
Comment (xmasterpiecex) [reply src/components/gameScene/animatedComp/AnimatedScrollForThemes.tsx]: Got it

**Review by uspiritwolf — APPROVED** [review]
